# Site settings
title: DentistSmile | Dental Jekyll Theme
description: "A responsive Jekyll theme for dental clinics."
baseurl: "/newifi" # the subpath of your site, e.g. /blog
url: "https://arvinwang8721.github.io" # the name of your domain
logo_url: svg/min/logo.png

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Newifi
    hero_description: Newifi technology for your wireless network.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: +8619957825032
    email: enjoy.wifi@gmail.com
    address: 4th Floor, 1st Building, Huangqiang Electronic World <br> Shenzhen - China

# Opening hours
monday_friday: 9:00 – 18:00 CST
saturday: 10:00 – 17:00 CST
sunday: 10:00 – 15:00 CST

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: No.13B005 4th Floor, 1st Building, Huaqiang Electronic World, Futian District, ShenZhen, China
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2020 newifi - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
